# Generated by Django 5.0.4 on 2024-05-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_recipe_update_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='update_by_user',
            new_name='updated_by_user',
        ),
    ]
