# Generated by Django 5.0.4 on 2024-05-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_rename_update_by_user_recipe_updated_by_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
